version: "3.9"


volumes:
  postgres_data_dev:


services:
  db:
    image: postgres:13.0
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env

  web:
    build: src
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/opt/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

#  node_kostil:
#    build: ./node-kostil
#    command: [ "npm", "run", "dev" ]
#    ports:
#      - 8001:8080
#    volumes:
#      - ./node-kostil/src/:/usr/src/app/src/
